### ISSUE TITLE
This doesn't support help option and failing on few projects with below Error

### ISSUE THREAD

**Issue by sumitnagal** [igrigorik/bugspots#33]
bash-3.2$ git bugspots --help 
No manual entry for git-bugspots

mtvd125a0000% git-bugspots 
Scanning /Users/aaaa/dev/project/src repo
/usr/local/lib/ruby/gems/2.3.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:20:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
        from /usr/local/lib/ruby/gems/2.3.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:20:in `block in scan'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:19:in `each'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:19:in `scan'
        from /usr/local/lib/ruby/gems/2.3.0/gems/bugspots-0.2.1/bin/bugspots:52:in `<top (required)>'
        from /usr/local/bin/bugspots:23:in `load'
        from /usr/local/bin/bugspots:23:in `<main>'

**Comment by lucywyman** [comment]
Hello! bugspots is it's own project, not a git subcommand. The command you're looking for is `bugspots --help`.

**Comment by igrigorik** [comment]
@lucywyman we do ship https://github.com/igrigorik/bugspots/blob/master/bin/git-bugspots. 

This looks like an encoding error =/
