### ISSUE TITLE
This doesn't work with single branch, which is not master 

### ISSUE THREAD

**Issue by sumitnagal** [igrigorik/bugspots#34]
bash-3.2$ git bugspots 
Scanning /Users/aaa/GitHub/service repo
/usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:13:in `scan': no such branch in the repo: master (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/bin/bugspots:52:in `<top (required)>'
	from /usr/local/bin/bugspots:22:in `load'
	from /usr/local/bin/bugspots:22:in `<main>'
bash-3.2$ git branch 
* develop
bash-3.2$ git checkout -B master 
Switched to a new branch 'master'
bash-3.2$ git branch 
  develop
* master
bash-3.2$ git bugspots 
Scanning /Users/aaaa/GitHub/service repo
	Found xxx bugfix commits, with xxx hotspots:

**Comment by steveax** [comment]
While the options are not explicitly listed in the README, they are in the help and you can use the branch option `-b` to specify a branch:

```
➜   bugspots --help
Usage: bugspots /path/to/git/repo
    -b, --branch [name]              branch to crawl
    -d, --depth [depth]              depth of log crawl (integer)
    -w, --words ["w1,w2"]            bugfix indicator word list, ie: "fixes,closed"
    -r, --regex [regex]              bugfix indicator regex, ie: "fix(es|ed)?" or "/fixes #(\d+)/i"
        --display-timestamps         show timestamps of each identified fix commit
```
