### ISSUE TITLE
Invalid byte code issue

### ISSUE THREAD

**Issue by sumitnagal** [igrigorik/bugspots#37]
Getting below failure on our code base .. Same stuff is working on smaller and other projects 

bugspots /Users/sumitnagal/dev/src/ -b develop  
Scanning /Users/sumitnagal/dev/src/ repo
/usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:20:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
	from /usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:20:in `block in scan'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:19:in `each'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/lib/bugspots/scanner.rb:19:in `scan'
	from /usr/local/lib/ruby/gems/2.4.0/gems/bugspots-0.2.1/bin/bugspots:52:in `<top (required)>'
	from /usr/local/bin/bugspots:22:in `load'
	from /usr/local/bin/bugspots:22:in `<main>'

**Comment by igrigorik** [comment]
Any chance you can isolate the file to reproduce the error?

**Comment by sumitnagal** [comment]
I am not sure how to get that file information if you can tell me what content it is looking via which git command, I can re-run and identify the file. there is no way I can run in debug mode and get more information.

**Comment by lindboe** [comment]
I ran into the same issue with the [puppet repo](https://github.com/puppetlabs/puppet).

I added some print debugging to figure out what was up:

```
    walker.each do |commit|
      begin
      if commit.message =~ regex
        files = commit.diff(commit.parents.first).deltas.collect do |d|
          d.old_file[:path]
        end
        fixes << Fix.new(commit.message.split("\n").first, commit.time, files)
      end
      rescue ArgumentError
        puts "failed for commit #{commit.message}"
      end
    end
```

It printed the problem commit (at end of comment) which did actually contain invalid UTF-8.
I'd suggest adding better error handling to the scan method, similar to my debugging would work, and just skipping any commits that aren't readable, but warn about them. There was only one issue in all of puppet's commits so the tool was still useful for me.

**Comment by Stantheman** [comment]
For future folks that come across this issue, it's already been fixed by this commit:

https://github.com/igrigorik/bugspots/commit/f7cec150738a2525a1dbf517f10e6b83a44df99a

You can install from master until a new version of the gem is cut:

- clone the repo
- `gem build bugspots.gemspec`
- `gem install bugspots-0.2.1.gem`

I think this issue can be closed, although it might be useful to keep open until a new release is cut. Thanks for the very helpful tool!

**Comment by igrigorik** [comment]
Oi, we still haven't released that? My bad!

Thanks for the nudge. 0.2.2 should be up on rubygems now.

**Comment by sumitnagal** [comment]
I will validate and keep you posted
